/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import granja.Control;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author SANTY
 */
public class Consultas extends javax.swing.JFrame {

    Menu menu;
    MenuPapa info = new MenuPapa();
    MenuFresa info2 = new MenuFresa();
  
    public Consultas() {
        initComponents();
        fillcombofresa();
        fillcombopapa();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Combofresa = new javax.swing.JComboBox<>();
        Combopapa = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("CONSULTAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 30));

        salirBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 70, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Tiempo restante: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Calcular tiempo restante para la cosecha");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        Combofresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combofresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombofresaActionPerformed(evt);
            }
        });
        getContentPane().add(Combofresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        Combopapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Combopapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Cultivo papa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Cultivo Fresa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nature-background-of-a-grassy-landscape_1048-1305.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        menu = new Menu();
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
      System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void CombofresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombofresaActionPerformed
      
    }//GEN-LAST:event_CombofresaActionPerformed

    private void fillcombofresa(){
         Statement st;
       
       try{
       st=Control.cn.createStatement();
       ResultSet rs = st.executeQuery("Select * from fresa;");
       while(rs.next()){
        String item=rs.getString("id");
        Combofresa.addItem(item);
            }
       } catch (SQLException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void fillcombopapa(){
         Statement st;
       
       try{
       st=Control.cn.createStatement();
       ResultSet rs = st.executeQuery("Select * from papa;");
       while(rs.next()){
        String item=rs.getString("id");
        Combopapa.addItem(item);
            }
       } catch (SQLException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private class ItemHandlerfresa implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
        java.util.Date fecha = new Date();
        int dias = 0;
        Statement st;
            try {
                st = Control.cn.createStatement();
          ResultSet rs = st.executeQuery("Select * from fresa;");
          while(rs.next()){
          if(e.getSource()==Combofresa)
              if(Combofresa.getSelectedItem().equals(rs.getDate("id"))) 
		dias=(int) ((fecha.getTime()-rs.getDate("fecha").getTime())/86400000);
                  time.setText("A SU CULTIVO LE FALTAN: "+dias+" DIAS PARA SER RECOGIDO");}
            } catch (SQLException ex) {
                Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
            }
      
        }
        
    }
     private class ItemHandlerpapa implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
        java.util.Date fecha = new Date();
        int dias = 0;
        Statement st;
            try {
                st = Control.cn.createStatement();
          ResultSet rs = st.executeQuery("Select * from papa;");
          while(rs.next()){
          if(e.getSource()==Combofresa)
              if(Combofresa.getSelectedItem().equals(rs.getDate("id"))) 
		dias=(int) ((fecha.getTime()-rs.getDate("fecha").getTime())/86400000);
                  time.setText("A SU CULTIVO LE FALTAN: "+dias+" DIAS PARA SER RECOGIDO");}
            } catch (SQLException ex) {
                Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
            }
      
        }
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combofresa;
    private javax.swing.JComboBox<String> Combopapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel time;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
