/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author SANTY
 */
public class Cultivo extends javax.swing.JFrame {

    Menu menu; 
    public Cultivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        cultivofresaBtn = new javax.swing.JButton();
        cultivofresaBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("MENU MANEJO DE CULTIVOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        salirBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, -1));

        cultivofresaBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cultivofresaBtn.setText("CULTIVO DE FRESA");
        cultivofresaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultivofresaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cultivofresaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, -1));

        cultivofresaBtn1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cultivofresaBtn1.setText("CULTIVO DE PAPA");
        cultivofresaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultivofresaBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(cultivofresaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("...Proximamente más cultivos...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nature-background-of-a-grassy-landscape_1048-1305.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        menu = new Menu();
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
      System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void cultivofresaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cultivofresaBtnActionPerformed
    MenuFresa info2 = new MenuFresa();
    info2.setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_cultivofresaBtnActionPerformed

    private void cultivofresaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cultivofresaBtn1ActionPerformed
       MenuPapa inf=new MenuPapa();
       inf.setVisible(true);
       setVisible(false);
       
    }//GEN-LAST:event_cultivofresaBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cultivofresaBtn;
    private javax.swing.JButton cultivofresaBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
