/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import granja.Control;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Operaciones;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class InfoIncialFresa extends javax.swing.JFrame {
    MenuFresa ob = new MenuFresa();
    public static String data;
    public static String ab;
    public static String pr;
    Operaciones obOp = new Operaciones();
    public InfoIncialFresa() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        semplanFresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cargarFresa = new javax.swing.JButton();
        fechaFresa = new javax.swing.JTextField();
        inversionFresa = new javax.swing.JTextField();
        tamañoFresa = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fondoframe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("FRESA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Semillas plantadas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        semplanFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semplanFresaActionPerformed(evt);
            }
        });
        semplanFresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semplanFresaKeyTyped(evt);
            }
        });
        getContentPane().add(semplanFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 90, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Costo total inversion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        cargarFresa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cargarFresa.setText("CARGAR");
        cargarFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFresaActionPerformed(evt);
            }
        });
        getContentPane().add(cargarFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 100, 40));

        fechaFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFresaActionPerformed(evt);
            }
        });
        getContentPane().add(fechaFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, -1));

        inversionFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversionFresaActionPerformed(evt);
            }
        });
        inversionFresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inversionFresaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inversionFresaKeyTyped(evt);
            }
        });
        getContentPane().add(inversionFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, -1));

        tamañoFresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamañoFresaKeyTyped(evt);
            }
        });
        getContentPane().add(tamañoFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Fecha");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("INFORMACION INICIAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Tamaño");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 139, -1, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Ej: 2016-05-26");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Ingrese el numero exacto ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Numero de metros cuadrados");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Ej: 100");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Fecha de recoleccion del cultivo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fresa.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 70));

        fondoframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nature-background-of-a-grassy-landscape_1048-1305.jpg"))); // NOI18N
        getContentPane().add(fondoframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cargarFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFresaActionPerformed
        try {
            PreparedStatement pps=Control.cn.prepareStatement("INSERT INTO fresa(establecimiento,abono,problema,tamaño,fecha,costo_total)VALUES(?,?,?,?,?,?);");
            SimpleDateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");
            Date fechaculf= dateformat.parse(fechaFresa.getText());
            pps.setString(1, data);
            pps.setString(2, ab);
            pps.setString(3, pr);
            pps.setInt(4, Integer.parseInt(tamañoFresa.getText()));
            pps.setDate(5, (java.sql.Date) fechaculf);
            pps.setInt(6, Integer.parseInt(inversionFresa.getText()));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(InfoIncialFresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(InfoIncialFresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cargarFresaActionPerformed

    private void fechaFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFresaActionPerformed

    private void inversionFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversionFresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionFresaActionPerformed

    private void semplanFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semplanFresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semplanFresaActionPerformed

    private void semplanFresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semplanFresaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_semplanFresaKeyTyped

    private void tamañoFresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamañoFresaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoFresaKeyTyped

    private void inversionFresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inversionFresaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionFresaKeyPressed

    private void inversionFresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inversionFresaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_inversionFresaKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarFresa;
    private javax.swing.JTextField fechaFresa;
    private javax.swing.JLabel fondoframe;
    private javax.swing.JTextField inversionFresa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton salir;
    private javax.swing.JTextField semplanFresa;
    private javax.swing.JTextField tamañoFresa;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
