/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import granja.Control;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Operaciones;
import static vista.InfoIncialFresa.ab;
import static vista.InfoIncialFresa.data;
import static vista.InfoIncialFresa.pr;
import vista.Menu;

public class InfoIncialPapa extends javax.swing.JFrame {
public static String data;
    public static String ab;
    public static String pr;

    Operaciones obOp = new Operaciones();
    public InfoIncialPapa() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        semplanPapa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cargarFresa = new javax.swing.JButton();
        fechaPapa = new javax.swing.JTextField();
        inversionPapa = new javax.swing.JTextField();
        tamañoPapa = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fondoframe = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("PAPA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Semillas plantadas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        semplanPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semplanPapaActionPerformed(evt);
            }
        });
        semplanPapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semplanPapaKeyTyped(evt);
            }
        });
        getContentPane().add(semplanPapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Costo total inversion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        cargarFresa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cargarFresa.setText("CARGAR");
        cargarFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFresaActionPerformed(evt);
            }
        });
        getContentPane().add(cargarFresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 100, 40));

        fechaPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaPapaActionPerformed(evt);
            }
        });
        getContentPane().add(fechaPapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 90, -1));

        inversionPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversionPapaActionPerformed(evt);
            }
        });
        inversionPapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inversionPapaKeyTyped(evt);
            }
        });
        getContentPane().add(inversionPapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 90, -1));

        tamañoPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoPapaActionPerformed(evt);
            }
        });
        tamañoPapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamañoPapaKeyTyped(evt);
            }
        });
        getContentPane().add(tamañoPapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 90, -1));

        volver.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Fecha");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("INFORMACION INICIAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Tamaño");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 139, -1, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Ej: 03/03/2016");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Ingrese el numero exacto ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Numero de metros cuadrados");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Ej: 100");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Fecha de recoleccion del cultivo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papa.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 70));

        fondoframe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nature-background-of-a-grassy-landscape_1048-1305.jpg"))); // NOI18N
        getContentPane().add(fondoframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       MenuPapa ob = new MenuPapa();
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cargarFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFresaActionPerformed
try {
            PreparedStatement pps=Control.cn.prepareStatement("INSERT INTO papa(establecimiento,abono,problema,tamaño,fecha,costo_total)VALUES(?,?,?,?,?,?);");
            SimpleDateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");
            Date fechaculp= dateformat.parse(fechaPapa.getText());
            pps.setString(1, data);
            pps.setString(2, ab);
            pps.setString(3, pr);
            pps.setInt(4, Integer.parseInt(tamañoPapa.getText()));
            pps.setDate(5, (java.sql.Date) fechaculp);
            pps.setInt(6, Integer.parseInt(inversionPapa.getText()));
                       
        } catch (SQLException ex) {
            Logger.getLogger(InfoIncialFresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {        
        Logger.getLogger(InfoIncialPapa.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_cargarFresaActionPerformed

    private void fechaPapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaPapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaPapaActionPerformed

    private void inversionPapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversionPapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inversionPapaActionPerformed

    private void semplanPapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semplanPapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semplanPapaActionPerformed

    private void tamañoPapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoPapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoPapaActionPerformed

    private void semplanPapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semplanPapaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_semplanPapaKeyTyped

    private void tamañoPapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamañoPapaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoPapaKeyTyped

    private void inversionPapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inversionPapaKeyTyped
char c= evt.getKeyChar();
       if(c<0||c>9)
           evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_inversionPapaKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarFresa;
    private javax.swing.JTextField fechaPapa;
    private javax.swing.JLabel fondoframe;
    private javax.swing.JTextField inversionPapa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton salir;
    private javax.swing.JTextField semplanPapa;
    private javax.swing.JTextField tamañoPapa;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
