/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import granja.Control;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Estudiante
 */
public class LogIn extends javax.swing.JFrame {

Menu obMain=new Menu();
Registro winr=new Registro();
public static String usu;   
    boolean ing = false;

    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        ingreso = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        registro = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, -1));
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));

        ingreso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ingreso.setText("INGRESAR");
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 40));

        jToggleButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButton1.setText("SALIR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        registro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        registro.setText("REGISTRARSE");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 170, -1));

        aviso.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aviso.setText("Si no tiene usuario, debe crear uno");
        getContentPane().add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 270, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nature-background-of-a-grassy-landscape_1048-1305.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 320));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
          Statement st;
        String usu=usuario.getText();
        String cont=contraseña.getText();
        try {
            st = Control.cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM usuario;");
            
            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase(usuario.getText()) && rs.getString(2).equalsIgnoreCase(contraseña.getText())) {
                        setVisible(false);
                        obMain.setVisible(true);
                        usu=rs.getString(1);
                        DatosGenerales.usu=usuario.getText();
                } else {
                    System.out.println(rs.getString(1) + "\n" + usuario.getText() + "\n" + rs.getString(2) + "\n" + contraseña.getText());
                    aviso.setText("¡ERROR, USUARIO O CONTRASEÑA INCORRECTOS!");
                    aviso.setForeground(java.awt.Color.red);
                 }
            }

        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }


           

        
           
    }//GEN-LAST:event_ingresoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        winr=new Registro();
        winr.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_registroActionPerformed

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
       usuario.setText(null);
       usuario.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_usuarioMouseClicked




    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JPasswordField contraseña;
    public static javax.swing.JButton ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JButton registro;
    public static javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
