/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JLabel;

/**
 *
 * @author Mateo Chaparro
 */
public class Menu extends javax.swing.JFrame {
    
    DatosGenerales datos;
   
    
     Cultivo cultivo = new Cultivo();

    public JLabel getUsermenu() {
        return Usermenu;
    }

    public void setUsermenu(JLabel Usermenu) {
        this.Usermenu = Usermenu;
    }
    

    
    public Menu() {
        initComponents();
        //Usermenu.setText(LogIn.actuser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        datosgenBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Usermenu = new javax.swing.JLabel();
        consultasBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        crearcultivoBtn = new javax.swing.JButton();
        usermenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("¡Bienvenido!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        datosgenBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        datosgenBtn.setText("MODIFICAR DATOS GENERALES");
        datosgenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosgenBtnActionPerformed(evt);
            }
        });
        getContentPane().add(datosgenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("MENU DE OPCIONES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
        getContentPane().add(Usermenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 70, 20));

        consultasBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        consultasBtn.setText("CONSULTAS");
        consultasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasBtnActionPerformed(evt);
            }
        });
        getContentPane().add(consultasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 240, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, -1));

        crearcultivoBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        crearcultivoBtn.setText("CULTIVOS");
        crearcultivoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcultivoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(crearcultivoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 240, -1));

        usermenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main.png"))); // NOI18N
        getContentPane().add(usermenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datosgenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosgenBtnActionPerformed
        datos = new DatosGenerales();
        datos.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_datosgenBtnActionPerformed

    private void consultasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasBtnActionPerformed
        Consultas con=new Consultas();  
        con.setVisible(true);
    }//GEN-LAST:event_consultasBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void crearcultivoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcultivoBtnActionPerformed

       cultivo.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_crearcultivoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usermenu;
    private javax.swing.JButton consultasBtn;
    private javax.swing.JButton crearcultivoBtn;
    private javax.swing.JButton datosgenBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel usermenu;
    // End of variables declaration//GEN-END:variables
}
